apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::139355608147:role/eksctl-scrumptious-sheepdog-177358-NodeInstanceRole-aO14ZfBatjmQ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::139355608147:user/rahul
      username: rahul
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-15T14:38:57Z"
  name: aws-auth
  namespace: kube-system
  uid: 24004931-79b1-4656-a806-769a82484a30
