apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::139355608147:role/eksctl-floral-rainbow-1773164078-n-NodeInstanceRole-aWKu20OSvw0f
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::139355608147:user/shiva
      username: shiva
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-10T17:46:41Z"
  name: aws-auth
  namespace: kube-system
  uid: 3b5d2ed4-0955-4b45-8bef-83a21d334ae3
