apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::139355608147:role/eksctl-scrumptious-rainbow-1773235-NodeInstanceRole-5m0ohrbesBhV
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::139355608147:user/sai
      username: sai
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-11T13:33:18Z"
  name: aws-auth
  namespace: kube-system
  uid: 78d2aa8f-a741-4bc6-ad51-daefc87a08a2

