apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::139355608147:role/eksctl-scrumptious-rainbow-1773235-NodeInstanceRole-5m0ohrbesBhV
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::139355608147:user/sai
      username: sai
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-12T04:06:42Z"
  name: aws-auth
  namespace: kube-system
  uid: 7cff7aea-3258-4c62-8b11-5ead3a8c3ce4


