apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::139355608147:role/eksctl-floral-sheepdog-1773202165--NodeInstanceRole-L48GtuiDesY3
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::139355608147:user/sai
      username: sai
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-11T04:21:11Z"
  name: aws-auth
  namespace: kube-system
  uid: 05b64adf-12b6-4594-bb54-9e5051c0a8fe
