apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
    spec:
      serviceAccount: roboshop-mysql-secret-reader
      volumes:
      - name: mysql-secret
        emptyDir: {}
      containers:
      - name: mysql
        image: shivanathbabu/mysql:v2
        imagePullPolicy : Always
        volumeMounts:
        - mountPath: /tmp
          name: mysql-secret
      initContainers:
      - name: fetch-secret
        image: amazon/aws-cli
        command: 
        - sh 
        - -c 
        - aws secretsmanager get-secret-value --secret-id roboshop/mysql/password --query SecretString --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql_root_password.txt
        volumeMounts:
        - name: mysql-secret
          mountPath: /tmp

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-sa
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  selector:
    project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306