apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::139355608147:role/eksctl-ferocious-hideout-177625850-NodeInstanceRole-QPktTxI4lR4d
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::139355608147:user/shivanath
      username: shivanath
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T13:19:28Z"
  name: aws-auth
  namespace: kube-system
  uid: 526ffce8-34f3-44ba-9941-f65343ba4bae